export default {
    get layoutContainer() { return document.querySelector(".layout-container"); },
    get initializeLayout() { return document.querySelector(".initialize-layout"); },
    get loginLayout() { return document.querySelector(".login-layout"); },
    get verifyLayout() { return document.querySelector(".verify-layout"); },
    get sharedLayout() { return document.querySelector(".shared-layout"); },
    get outerCircleCover() { return document.querySelector(".outer-circle-cover"); },
    get innerCircleCover() { return document.querySelector(".inner-circle-cover"); },
    get curves() { return document.querySelector(".curves"); },
    get bottomUpperLine() { return document.querySelector(".bottom-upper-line"); },
    get bottomLowerLine() { return document.querySelector(".bottom-lower-line"); },
    get bottomLeftLine() { return document.querySelector(".bottom-left-line"); },
    get bottomRightLine() { return document.querySelector(".bottom-right-line"); },
    get verticalRollingDots() { return document.querySelector(".vertical-rolling-dots"); },
    get progressCircles() { return document.querySelector(".progress-circles"); },
    get outerProgressCircle() { return document.querySelector(".outer-progress-circle"); },
    get innerProgressCircle() { return document.querySelector(".inner-progress-circle"); },
    get systemAccessToImSystemTextBackground() { return document.querySelector(".system-access-to-im-system-text-background"); },
    get systemAccessToImSystemText() { return document.querySelector(".system-access-to-im-system-text"); },
    get systemVersionStraghtLinkModeText() { return document.querySelector(".system-version-straght-link-mode-text"); },
    get systemMiddleLine() { return document.querySelector(".system-middle-line"); },
    get leftBracketText() { return document.querySelector(".left-bracket-text"); },
    get rightBracketText() { return document.querySelector(".right-bracket-text"); },
    get initializingText() { return document.querySelector(".initializing-text"); },
    get finishedText() { return document.querySelector(".finished-text"); },
    get loginForm() { return document.querySelector(".login-form"); },
    get loginFormTopCover() { return document.querySelector(".login-form-top-cover"); },
    get loginFormLeftCover() { return document.querySelector(".login-form-left-cover"); },
    get loginFormRightCover() { return document.querySelector(".login-form-right-cover"); },
    get loginFormTopLine() { return document.querySelector(".login-form-top-line"); },
    get loginFormBottomLine() { return document.querySelector(".login-form-bottom-line"); },
    get loginFormHorizonRollingDots() { return document.querySelector(".login-form-horizon-rolling-dots"); },
    get loginFormSystemAccessToImSystemTextBackground() { return document.querySelector(".login-form .system-access-to-im-system-text-background"); },
    get loginFormSystemAccessToImSystemText() { return document.querySelector(".login-form .system-access-to-im-system-text"); },
    get loginFormSystemVersionStraghtLinkModeText() { return document.querySelector(".login-form .system-version-straght-link-mode-text"); },
    get loginFormSystemMiddleLine() { return document.querySelector(".login-form .system-middle-line"); },
    get loginFormAccountFieldBackground() { return document.querySelector(".login-form-account-field-background"); },
    get loginFormPasswordFieldBackground() { return document.querySelector(".login-form-password-field-background"); },
    get accountFieldContainer() { return document.querySelector(".account-field-container"); },
    get passwordFieldContainer() { return document.querySelector(".password-field-container"); },
    get accountFieldAsterisk() { return document.querySelector(".account-field-asterisk"); },
    get passwordFieldAsterisk() { return document.querySelector(".password-field-asterisk"); },
    get accountField() { return document.querySelector(".account-field"); },
    get passwordField() { return document.querySelector(".password-field"); },
    get loginButton() { return document.querySelector(".login-button"); },
    get avatarImg() { return document.querySelector(".avatar"); },
};
